type: map
mapping:
  =:
    type: map
    name: Service
    mapping:
      "image":
      "build":
      "command":
      "links":
        type: seq
        sequence:
          - type: str
            name: Link
      "external_links":
        type: seq
        sequence:
          - type: str
      "ports":
        type: seq
        sequence:
          - type: text
      "expose":
        type: seq
        sequence:
          - type: text
      "volumes":
        type: seq
        sequence:
          - type: str
      "volumes_from":
        type: seq
        sequence:
          - type: str
      "environment":
        name: Environment
        type: any
      "env_file":
        type: seq
        sequence:
          - type: str
      "net":
        type: seq
        sequence:
          - type: str
      "dns":
        name: DNS
        type: any
      "cap_add":
        type: seq
        sequence:
          - type: str
      "cap_drop":
        type: seq
        sequence:
          - type: str
      "dns_search":
        name: Search
        type: any
      "working_dir":
      "entrypoint":
      "user":
      "hostname":
      "domainname":
      "mem_limit":
        type: int
      "privileged":
      "restart":
      "stdin_open":
      "tty":
      "cpu_shares":
        type: int
